extends Node

# NAO USEI O CLASS_NAME POR QUE QUEM VAI INSTANCIAR A CLASSE
# E O AUTOLOAD DO GODOT
# PELO QUE PESQUISEI ISSO NAO GERA UMA CLASSE GLOBAL COMO AQULAS QUE 
# A GENTE CONHECE QUE DA ERRO, ISSO GERA COMO UM SINGLETON
# ELE CRIA UMA INSTANCIA GLOBAL DESSE SCRIPT, SEM REALMENTE SER GLOBAL
# QUALQUER COISA MUDAR

# SE USARMOS O CLASSE_NAME NA HORA DE ADICIONAR NO AUTOLOAD DA ERRO
# AI NAO DA PARA CRIAR UM SINGLETON ( AUTOLOAD ) COM O NOME DA CLASS_NAME


func _ready() -> void:
	TranslationServer.set_locale("pt_BR")
	
func set_traducao(codigo_linguagem) -> void:
	TranslationServer.set_locale(codigo_linguagem)
